# Generated by Django 4.2.4 on 2023-09-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(max_length=3, verbose_name='Material 3 Letter Code')),
                ('long_text', models.TextField(verbose_name='Material Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Material Price')),
                ('stock', models.SmallIntegerField(verbose_name='Current Stock')),
                ('packing_material', models.SmallIntegerField(verbose_name='Packing Material Reqd Qty')),
                ('is_packing', models.BooleanField(verbose_name='Is this a packing material')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order Id')),
                ('quantity', models.SmallIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Unit Price')),
                ('deliver_date', models.DateField(verbose_name='Delivery Date')),
                ('stage', models.CharField(choices=[('OR', 'Ordered'), ('PI', 'Picked'), ('PA', 'Packed'), ('SP', 'Shipped')], max_length=2)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_of', to='order.material')),
            ],
        ),
    ]
