# Generated by Django 4.2.4 on 2023-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_material_packing_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='packing_material',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Packing Material Reqd Qty'),
        ),
    ]
