# Generated by Django 4.2.4 on 2023-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_deliver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Packing Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Shipping Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_reference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Shipping Reference from ShipRocket'),
        ),
    ]
